### ISSUE TITLE
An exception of type 'System.TypeInitializationException' occurred

### ISSUE THREAD

**Issue by zachtdavis** [davidmarker/TradingApplication#1] opened 2017-07-21 22:30 UTC
An exception of type 'System.TypeInitializationException' occurred in TradingApplication.exe but was not handled in user code

Additional information: The type initializer for 'TradingApplication.Model.GDAXAPIClient' threw an exception.

Line 19-20 of Presenter.cs

I just tried to run your application in VS 2015 and 2017 and it will not get past this line. I have entered my API credentials into the XML, only modification I have made.

Thanks!

**Comment by davidmarker** [comment] 2017-07-22 00:32
Zach,

I'll try to find some time this weekend to take a look and try to reproduce.

**Comment by davidmarker** [comment] 2017-07-22 18:58
So, it looks like the issue is that my code is trying to access the APIData.xml file from the Model directory, relative to where the build .exe is at and the xml file isn't being copied to where the code is expecting it to be at runtime. I've changed my working copy of the code so it looks for the xml file in the same location as the .exe file and I'm now trying to figure out how to get the build process to copy the xml file to the build directory.

**Comment by davidmarker** [comment] 2017-07-22 19:22
I just merged in a fix. You should be able to edit the APIData.xml file in your solution and the edited file should be copied to the build target's directory.

**Closed by davidmarker** 2017-07-22 19:22 UTC
